# Generated by Django 5.2.18 on 2026-10-06 16:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate, unique=True)),
                ('notes_covered_count', models.PositiveIntegerField(default=0)),
                ('quizzes_completed_count', models.PositiveIntegerField(default=0)),
                ('tasks_completed_count', models.PositiveIntegerField(default=0)),
                ('study_minutes', models.PositiveIntegerField(default=25)),
                ('overall_progress_snapshot', models.FloatField(default=0.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
