# Generated by Django 5.2.18 on 2026-10-06 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudyResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='resources/')),
                ('filename', models.CharField(max_length=255)),
                ('file_type', models.CharField(choices=[('PDF', 'PDF Document'), ('TXT', 'Text File'), ('CSV', 'CSV Spreadsheet'), ('OTHER', 'Study Resource')], default='PDF', max_length=20)),
                ('file_size', models.PositiveIntegerField(default=0, help_text='File size in bytes')),
                ('subject', models.CharField(default='Python', max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
