# Generated by Django 5.2.18 on 2026-10-06 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocol', models.CharField(choices=[('SOCKET', 'TCP Socket'), ('SMTP', 'SMTP Email'), ('FTP', 'FTP Transfer')], max_length=20)),
                ('action', models.CharField(max_length=120)),
                ('status', models.CharField(default='Success', max_length=40)),
                ('details', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
